name: instagram

on:
  push:
    branches: [ INSTALLATION IN TERMUX ]
  pull_request:
    branches: [ INSTALLATION IN TERMUX ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '206.1.0.34.121'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x choicebot.sh
    - name: nano hashtags.txt (#prince)
$ ./choicebot.sh
      run:  ./choicebot.sh
 
